import { Metadata } from "next";
import { CodeBlock } from "../_components/code-block";

export const metadata: Metadata = {
  title: "configuration | rivanna.dev docs",
  description: "rv config file reference and environment setup",
};

export default function ConfigurationPage() {
  return (
    <div className="space-y-8">
      <section>
        <h2 className="text-xl font-semibold mb-4">configuration</h2>
        <p className="text-gray-600 mb-6">
          rv stores its configuration in{" "}
          <code className="text-orange-accent">~/.rv/config.toml</code>. created
          automatically by <code className="text-orange-accent">rv init</code>.
        </p>
      </section>

      <section
        id="config-file"
        className="border border-gray-200 p-4 sm:p-6 space-y-4"
      >
        <h3 className="text-lg font-semibold text-black">config file</h3>
        <p className="text-sm text-gray-600">
          full example of{" "}
          <code className="text-orange-accent">~/.rv/config.toml</code>:
        </p>
        <CodeBlock>
          <code className="text-sm text-black whitespace-pre">{`[connection]
host = "rivanna"
user = "abc1de"
hostname = "rivanna.hpc.virginia.edu"

[defaults]
account = "mygroup"
gpu_type = "a6000"
time = "2:59:00"
partition = "gpu-a6000"
ai_naming = true
ai_api_key = "sk-..."

[paths]
scratch = "/scratch/abc1de"
home = "/home/abc1de"

[notifications]
enabled = true
email = "abc1de@virginia.edu"
token = "..."  # auto-generated by rv init

[scratch_keepalive]
enabled = true  # default: true

[shared]
hf_cache = "/standard/mygroup/.cache/huggingface"  # optional`}</code>
        </CodeBlock>
      </section>

      <section
        id="defaults"
        className="border border-gray-200 p-4 sm:p-6 space-y-4"
      >
        <h3 className="text-lg font-semibold text-black">defaults</h3>
        <p className="text-sm text-gray-600 mb-3">
          default values used when flags are not specified on the command line:
        </p>
        <div className="overflow-x-auto">
          <table className="w-full text-sm border border-gray-200">
            <thead>
              <tr className="bg-gray-50 text-left">
                <th className="px-3 py-2 border-b border-gray-200 font-medium">
                  key
                </th>
                <th className="px-3 py-2 border-b border-gray-200 font-medium">
                  description
                </th>
                <th className="px-3 py-2 border-b border-gray-200 font-medium">
                  example
                </th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">account</td>
                <td className="px-3 py-2 text-gray-600">
                  Slurm account (allocation group)
                </td>
                <td className="px-3 py-2 text-gray-500 text-xs">mygroup</td>
              </tr>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">gpu_type</td>
                <td className="px-3 py-2 text-gray-600">
                  default GPU type when --type is omitted
                </td>
                <td className="px-3 py-2 text-gray-500 text-xs">a6000</td>
              </tr>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">time</td>
                <td className="px-3 py-2 text-gray-600">default walltime</td>
                <td className="px-3 py-2 text-gray-500 text-xs">2:59:00</td>
              </tr>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">partition</td>
                <td className="px-3 py-2 text-gray-600">
                  default Slurm partition
                </td>
                <td className="px-3 py-2 text-gray-500 text-xs">gpu-a6000</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section
        id="notifications"
        className="border border-gray-200 p-4 sm:p-6 space-y-4"
      >
        <h3 className="text-lg font-semibold text-black">notifications</h3>
        <p className="text-sm text-gray-600">
          rv can email you when jobs complete or fail. notifications are sent to
          your @virginia.edu address via HMAC-signed webhooks.
        </p>
        <p className="text-sm text-gray-600">
          enable during <code className="text-orange-accent">rv init</code> or
          set manually in config.toml:
        </p>
        <CodeBlock>
          <code className="text-sm text-black whitespace-pre">{`[notifications]
enabled = true
email = "abc1de@virginia.edu"`}</code>
        </CodeBlock>
        <p className="text-xs text-gray-500">
          notification events: COMPLETED, FAILED, TIMEOUT, RESUBMITTED
          (checkpoint-restart).
        </p>
      </section>

      <section
        id="ai-naming"
        className="border border-gray-200 p-4 sm:p-6 space-y-4"
      >
        <h3 className="text-lg font-semibold text-black">ai naming</h3>
        <p className="text-sm text-gray-600">
          rv can auto-generate descriptive job names using an AI model. set your
          API key in config.toml — rv auto-detects the provider from the key
          prefix:
        </p>
        <div className="overflow-x-auto mt-2">
          <table className="w-full text-sm border border-gray-200">
            <thead>
              <tr className="bg-gray-50 text-left">
                <th className="px-3 py-2 border-b border-gray-200 font-medium">
                  key prefix
                </th>
                <th className="px-3 py-2 border-b border-gray-200 font-medium">
                  provider
                </th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">sk-ant-</td>
                <td className="px-3 py-2 text-gray-600">Anthropic</td>
              </tr>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">sk-</td>
                <td className="px-3 py-2 text-gray-600">OpenAI</td>
              </tr>
            </tbody>
          </table>
        </div>
        <CodeBlock>
          <code className="text-sm text-black whitespace-pre">{`[defaults]
ai_naming = true
ai_api_key = "sk-ant-..."`}</code>
        </CodeBlock>
      </section>

      <section
        id="environment-variables"
        className="border border-gray-200 p-4 sm:p-6 space-y-4"
      >
        <h3 className="text-lg font-semibold text-black">
          environment variables
        </h3>
        <p className="text-sm text-gray-600">
          use <code className="text-orange-accent">rv env</code> to manage
          variables that are injected into every job. these are stored remotely
          in env files and loaded at job start. useful for API keys, model
          paths, and other secrets.
        </p>
        <CodeBlock className="mb-2">
          <code className="text-sm text-black">
            rv env set HF_TOKEN hf_abc123...
          </code>
        </CodeBlock>
        <CodeBlock className="mb-2">
          <code className="text-sm text-black">rv env list</code>
        </CodeBlock>
        <CodeBlock>
          <code className="text-sm text-black">rv env rm HF_TOKEN</code>
        </CodeBlock>
        <p className="text-xs text-gray-500 mt-2">
          rv also auto-sets these variables in every job: OMP_NUM_THREADS,
          TOKENIZERS_PARALLELISM, HF_HOME, VLLM_CACHE_DIR, RV_CHECKPOINT_DIR.
        </p>
      </section>

      <section
        id="scratch-keepalive"
        className="border border-gray-200 p-4 sm:p-6 space-y-4"
      >
        <h3 className="text-lg font-semibold text-black">scratch keepalive</h3>
        <p className="text-sm text-gray-600">
          Rivanna&apos;s scratch filesystem has a 90-day purge policy — files
          not accessed in 90 days are automatically deleted. this would destroy
          your venv, environment variables, and caches.
        </p>
        <p className="text-sm text-gray-600">
          rv automatically prevents this by touching all files under{" "}
          <code className="text-orange-accent">/scratch/user/.rv/</code> and
          cache directories once per day (on the first rv command of the day).
          this runs in the background and adds no latency to your commands.
        </p>
        <p className="text-sm text-gray-600">enabled by default. to disable:</p>
        <CodeBlock>
          <code className="text-sm text-black whitespace-pre">{`[scratch_keepalive]
enabled = false`}</code>
        </CodeBlock>
      </section>

      <section
        id="shared-storage"
        className="border border-gray-200 p-4 sm:p-6 space-y-4"
      >
        <h3 className="text-lg font-semibold text-black">shared storage</h3>
        <p className="text-sm text-gray-600">
          if you&apos;re part of a lab group with access to persistent group
          storage (<code className="text-orange-accent">/standard/</code> or{" "}
          <code className="text-orange-accent">/project/</code>), rv can use it
          as a shared HuggingFace model cache. this avoids every lab member
          downloading the same large models to their own scratch.
        </p>
        <p className="text-sm text-gray-600">
          <code className="text-orange-accent">rv init</code> automatically
          detects group directories via{" "}
          <code className="text-orange-accent">hdquota</code> and offers to set
          this up. if you already have models in{" "}
          <code className="text-orange-accent">
            /scratch/user/.cache/huggingface
          </code>
          , rv will offer to migrate them to the shared location. rv also checks
          the shared filesystem&apos;s capacity — if it&apos;s over 80% full,
          you&apos;ll see a warning before proceeding.
        </p>
        <p className="text-sm text-gray-600">
          you can also configure it manually:
        </p>
        <CodeBlock>
          <code className="text-sm text-black whitespace-pre">{`[shared]
hf_cache = "/standard/mygroup/.cache/huggingface"`}</code>
        </CodeBlock>
        <p className="text-xs text-gray-500">
          the shared directory is created with group-writable setgid permissions
          (chmod g+rwxs) so all lab members can read and write models. group
          storage is persistent — not subject to the 90-day scratch purge. when
          active, both{" "}
          <code className="text-orange-accent">~/.cache/huggingface</code> and{" "}
          <code className="text-orange-accent">
            /scratch/user/.cache/huggingface
          </code>{" "}
          are symlinked to the shared location.
        </p>
      </section>

      <section
        id="paths"
        className="border border-gray-200 p-4 sm:p-6 space-y-4"
      >
        <h3 className="text-lg font-semibold text-black">paths</h3>
        <p className="text-sm text-gray-600 mb-3">
          rv organizes remote files under your scratch directory:
        </p>
        <div className="overflow-x-auto">
          <table className="w-full text-sm border border-gray-200">
            <thead>
              <tr className="bg-gray-50 text-left">
                <th className="px-3 py-2 border-b border-gray-200 font-medium">
                  path
                </th>
                <th className="px-3 py-2 border-b border-gray-200 font-medium">
                  purpose
                </th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">
                  /scratch/user/.rv/
                </td>
                <td className="px-3 py-2 text-gray-600">rv home directory</td>
              </tr>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">
                  /scratch/user/.rv/logs/
                </td>
                <td className="px-3 py-2 text-gray-600">job output logs</td>
              </tr>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">
                  /scratch/user/.rv/env/
                </td>
                <td className="px-3 py-2 text-gray-600">
                  environment variable files
                </td>
              </tr>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">
                  /scratch/user/.rv/venv/
                </td>
                <td className="px-3 py-2 text-gray-600">
                  persistent Python venv (torch + ray pre-installed)
                </td>
              </tr>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">
                  /scratch/user/rv-workspaces/
                </td>
                <td className="px-3 py-2 text-gray-600">
                  synced project workspaces
                </td>
              </tr>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">
                  /scratch/user/.cache/huggingface/
                </td>
                <td className="px-3 py-2 text-gray-600">
                  HuggingFace model cache (HF_HOME)
                </td>
              </tr>
              <tr className="border-b border-gray-100">
                <td className="px-3 py-2 font-mono text-xs">
                  /scratch/user/.cache/uv/
                </td>
                <td className="px-3 py-2 text-gray-600">uv package cache</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="text-xs text-gray-500">
          scratch storage is high-performance (Weka filesystem, ~1.5 GB/s
          write). files are{" "}
          <a
            href="https://www.rc.virginia.edu/userinfo/storage/non-sensitive-data/#scratch"
            className="text-orange-accent underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            not backed up
          </a>{" "}
          and subject to a 90-day purge policy.
        </p>
      </section>
    </div>
  );
}
