import type { GPUSpec, GPUType } from "./types.ts";

export const GPU_SPECS: Record<GPUType, GPUSpec> = {
  mig: {
    partition: "gpu-mig",
    gres: "gpu:1g.10gb",
    vramGB: 10,
    suPerGPUHour: 0,
    maxPerUser: 28,
    maxPerJob: 1,
    maxWalltime: "3-00:00:00",
    perNode: 56,
  },
  rtx3090: {
    partition: "interactive-rtx3090",
    gres: "gpu:rtx3090",
    vramGB: 24,
    suPerGPUHour: 113.23,
    maxPerUser: 2,
    maxPerJob: 2,
    maxWalltime: "12:00:00",
    perNode: 4,
  },
  a6000: {
    partition: "gpu-a6000",
    gres: "gpu:a6000",
    vramGB: 48,
    suPerGPUHour: 142.73,
    maxPerUser: 32,
    maxPerJob: 8,
    maxWalltime: "3-00:00:00",
    perNode: 8,
  },
  a40: {
    partition: "gpu-a40",
    gres: "gpu:a40",
    vramGB: 48,
    suPerGPUHour: 186.69,
    maxPerUser: 32,
    maxPerJob: 8,
    maxWalltime: "3-00:00:00",
    perNode: 8,
  },
  a100_40: {
    partition: "gpu-a100-40",
    gres: "gpu:a100",
    vramGB: 40,
    suPerGPUHour: 463.81,
    maxPerUser: 32,
    maxPerJob: 8,
    maxWalltime: "3-00:00:00",
    perNode: 8,
  },
  a100_80: {
    partition: "gpu-a100-80",
    gres: "gpu:a100",
    vramGB: 80,
    suPerGPUHour: 508.89,
    maxPerUser: 32,
    maxPerJob: 8,
    maxWalltime: "3-00:00:00",
    perNode: 8,
    features: ["gpupod", "a100_80gb"],
    hasInfiniBand: true,
    hasNVLink: true,
  },
  v100: {
    partition: "gpu-v100",
    gres: "gpu:v100",
    vramGB: 32,
    suPerGPUHour: 20.96,
    maxPerUser: 32,
    maxPerJob: 4,
    maxWalltime: "3-00:00:00",
    perNode: 4,
  },
  h200: {
    partition: "gpu-h200",
    gres: "gpu:h200",
    vramGB: 141,
    suPerGPUHour: 816.67,
    maxPerUser: 4,
    maxPerJob: 4,
    maxWalltime: "3-00:00:00",
    perNode: 8,
  },
} as const;

export const SCHEDULER_CONFIG = {
  backfillResolutionSeconds: 600,
  schedMinIntervalSeconds: 2,
  priorityDecayHalfLifeDays: 7,
  priorityMaxAgeDays: 28,
  preemptMode: "OFF",
  defaultWalltime: "5:00:00",
  recommendedWalltime: "2:59:00",
  maxSubmissions: 10000,
} as const;

export const PATHS = {
  rvDir: (user: string) => `/scratch/${user}/.rv`,
  logs: (user: string) => `/scratch/${user}/.rv/logs`,
  envFiles: (user: string) => `/scratch/${user}/.rv/env`,
  workspaces: (user: string) => `/scratch/${user}/rv-workspaces`,
  cache: {
    uv: (user: string) => `/scratch/${user}/.cache/uv`,
    pip: (user: string) => `/scratch/${user}/.cache/pip`,
    hf: (user: string) => `/scratch/${user}/.cache/huggingface`,
  },
} as const;
